### ISSUE TITLE
Zero Shapiro may break if Oops All 6s is sold mid-round

### ISSUE THREAD

**Issue by english5040** [Firch/Bunco#18]
Starting with a base prob. of 2, scoring an unranked card makes it 2.3; selling Oops makes it 1.15 .

Proposed: played cards with ... rank give X0.3 to probabilities this round when scored. (Currently YYY to probabilities)

**Comment by Firch** [comment]
Fixed in https://github.com/Firch/Bunco/commit/05bff2fa22700d622842dedd3c67d64cdcaf852d
