### ISSUE TITLE
Cards destroyed by Dread are not "fully" destroyed?

### ISSUE THREAD

**Issue by VexyRS** [Firch/Bunco#20]
![2379780_68](https://github.com/Firch/Bunco/assets/48223567/9f0ffa9f-d56b-417f-962a-69efb957923e)

Cards destroyed by dread still appear in hand, but without sprites.

**Comment by english5040** [comment]
What version of Bunco are you using?

**Comment by VexyRS** [comment]
![image](https://github.com/user-attachments/assets/e0e4e55b-9071-46fd-ad40-66b6e716a1dd)

**Comment by english5040** [comment]
Looks like you're using Bunco 4.2; Dread is way more buggy in version 4.2 than in the main branch.

You can move to Steamodded 1.0 + Bunco main if you'd like, it has compatibility with old mods now. Ask on the Discord if you need help switching
