### ISSUE TITLE
Prehistoric Joker interacting inconsistently with Stone Cards

### ISSUE THREAD

**Issue by ppunktalex** [Firch/Bunco#26]
From what I can tell, when PJ checks a Stone card for whether a card with its suit and rank has already been played, it uses the underlying card's suit and rank, which is impossible to check unless the card has been Tower'd.
Possible solutions:
- Stone cards always trigger PJ because Stone cards technically all have the same rank and suit, which is to say none.
- Stone cards can't get the multiplier from PJ at all because there's no suit and rank to compare.

**Comment by Firch** [comment]
I can't reproduce your issue, stone cards are already should be covered by Prehistoric Joker (it can't use stone cards as suit and rank reference, therefore it never triggers on stone cards). Which version are you on?

**Comment by ppunktalex** [comment]
The version number on my folder reads 4.2.

**Comment by Firch** [comment]
4.2 is no longer supported, if you want to use the newest version use Steamodded 1.0 and the indev version of Bunco, which you can find by downloading the source code
