### ISSUE TITLE
No Releases page

### ISSUE THREAD

**Issue by MisterIkkus** [Firch/Bunco#32]
Where is the releases page?

**Comment by Firch** [comment]
Currently there's no release for the 1.0 version of Steamodded. 0.9.8 versions are no longer supported, and were hidden to avoid confusion. To download Bunco for 0.9.8 use the ['old' Branch](https://github.com/Firch/Bunco/tree/old) of the mod.

**Comment by MisterIkkus** [comment]
Thank you.
