### ISSUE TITLE
Printer and cups'n balls not working properly

### ISSUE THREAD

**Issue by KrispyHappy** [Firch/Bunco#38]
To elaborate
Printer's ability seems to not work at all and when you try to reem cups'n balls with any booster pack missing the game crashes.

**Comment by Firch** [comment]
Fixed in https://github.com/Firch/Bunco/commit/b800f9124304e55e89dd6695dae090e20ae24c8c and https://github.com/Firch/Bunco/commit/3ba162631c98c00aca9e422560e1fe8b0bf17526
