### ISSUE TITLE
The Depth's tags can lock up the shop

### ISSUE THREAD

**Issue by flakywanderer** [Firch/Bunco#39]
After defeating The Depths boss blind, the next shop can become completely unresponsive to mouse input. I'm not completely sure what causes it, but from what I can tell it seems to occur when a tag would be applied to a joker that already has modifiers on it. 

It can be worked around by exiting the shop while the shop is still in its transitioning-in animation.

**Comment by Firch** [comment]
Fixed in https://github.com/Firch/Bunco/commit/d93141c05251053821e69f67d2c3874da3ac29dd
