### ISSUE TITLE
License Plate crashes the game when deck is empty.

### ISSUE THREAD

**Issue by pinkmaggit-hub** [Firch/Bunco#41]
The crash says `Bunco.lua"]:1643: attempt to index a nil value`. 
It happens because when the deck is empty, the combination{} table can't be filled at line 1643, since there's no cards in deck to fill it. 
It can be fixed by adding `and #G.deck.cards ~= 0` to the `if` statement at line 1632 of Bunco.lua, like so:

![image (1)](https://github.com/user-attachments/assets/fc6b62e6-589b-4e2b-8ad6-745da3b14495)

However, with this workaround, when the deck is empty, the plate isn't updated at the end of Round.

**Comment by Firch** [comment]
Fixed in https://github.com/Firch/Bunco/commit/8501224f4773df320e2b55680e1af727d547b1b8
