### ISSUE TITLE
Game Crashes on Startup [attempt to call method 'new_suit' (a nil value)]

### ISSUE THREAD

**Issue by TheLemon27** [Firch/Bunco#44]
Hi, this mod causes my game to crash on startup and I have no idea why. Full error is below.

[crash.txt](https://github.com/user-attachments/files/17535360/crash.txt)

Thanks in advance!

**Comment by btj888** [comment]
You're likely on  the old version of Steamodded. Reinstall via this:
https://github.com/fosterbarnes/steamoddedEZinstaller

**Comment by TheLemon27** [comment]
that didnt work (i used the automatic installer btw)

**Comment by TheLemon27** [comment]
exact same crash, too

**Comment by Firch** [comment]
Old/wrong Steamodded. Refer to the Steamodded's main page

**Comment by TheLemon27** [comment]
I did that, it still crashes.

**Comment by Firch** [comment]
What version of the Steamodded appears in the upper-right corner of the screen when you launch the game without the mod?

**Comment by TheLemon27** [comment]
1.0.0~ALPHA-1206d-STEAMMODDED

**Comment by Firch** [comment]
And which version of the Bunco you downloaded - are you sure you didn't download an outdated one?

**Comment by TheLemon27** [comment]
I believe at the time it was the latest release, but it might be outdated by now: 4.2

**Comment by Firch** [comment]
4.2 Is an outdated version that was released for Steamodded 0.9.8, and it was even outdated at the time this issue was made. Download the mod from the source code, not from the releases (I have no idea how you even managed to do that because I hid them from the mod's main page exactly to avoid this kind of confusion)

**Comment by TheLemon27** [comment]
I have no idea how i did that either. thanks, I'll do that right now!

**Comment by TheLemon27** [comment]
that worked!

**Comment by Firch** [comment]
Glad to help! 🫡
