### ISSUE TITLE
Observatory bug - not registering planet cards in consumable area

### ISSUE THREAD

**Issue by NotJustNoise** [Firch/Bunco#47]
After obtaining Observatory through an extra voucher tag with Anaglyph Deck, I purchased an Earth card from the shop and left it in my consumable area. I played a Full House on the following blind (not a boss) and didn't get the x1.5 Mult - suspecting a bug. Any ideas?; If people want to see video evidence I can DM a vid since it is too large to send in this post.

**Comment by Firch** [comment]
Fixed in https://github.com/Firch/Bunco/commit/f978fd97263d3674637a87c0fddb4d22534ae038
