### ISSUE TITLE
disproportionality card issue

### ISSUE THREAD

**Issue by mommy742** [Firch/Bunco#48]
![image](https://github.com/user-attachments/assets/08400cdd-6e2c-479d-8e37-1b7a1a0a5332)
![image](https://github.com/user-attachments/assets/3ab9def8-09ec-43a5-9ca2-638423c659cd)

this is the issue and these are my mods. all of them are up to date at the current moment

**Comment by Firch** [comment]
This looks as intended, what's the issue?

**Comment by mommy742** [comment]
> This looks as intended, what's the issue?

oh i didnt know that. never mind
