### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by AnonTheMouse** [Firch/Bunco#7]
Running steammodded, game produces an error screen when launched. Tested with and without other mods present. Log doesn't scroll down, but an image of the on-screen portion is included. (Your discord link doesn't work.)

![error](https://github.com/Firch/Bunco/assets/2175384/8000fbc1-c388-44c0-a4dc-d1bf187c08d3)

**Comment by AnonTheMouse** [comment]
This hasn't stopped happening, by the way. Even with a fresh install of Balatro and no other mods installed, the issue persists.

**Comment by english5040** [comment]
Hello- I recommend posting in the Discord in the Steamodded thread if you are having trouble; this is more likely an issue with Steamodded. There are also some things to verify- have you verified Balatro's files in Steam, have you installed lovely and Steamodded (don't know if you are using 1.0?) correctly.

**Comment by AnonTheMouse** [comment]
As stated in the original post, the link to the Discord does not work.

**Comment by english5040** [comment]
I'm sorry, I have no idea what "Your discord link" is- try the Balatro discord -> modding

**Comment by Firch** [comment]
It looks like you're trying to install 1.0 version on top of 0.9.8 Steamodded. You should download the mod from ![the releases](https://github.com/Firch/Bunco/releases) to make it work with 0.9.8, instead of downloading source code, which is still not very stable.

**Comment by AnonTheMouse** [comment]
I did download it from the releases, though?

**Comment by english5040** [comment]
hey, it will probably be easier if you join the Balatro discord and ask there. Are you unable to find that Discord for some reason?

**Comment by AnonTheMouse** [comment]
I've said twice already that the Discord link doesn't work...

**Comment by english5040** [comment]
hey, I'm really sorry about all this. I am going to be very clear here: join the Balatro discord at https://discord.com/invite/balatro (not the one on this mod) and post in the modding channels
